# **5 Basic Functions in NumPy** 
The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:

- function 1:Reshape
- function 2:numpy.trace
- function 3:Clip
- function 4:count_nonzero
- function 5:numpy.where
- function 5:numpy.compress





In [51]:
!pip install jovian --upgrade -q

In [52]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [54]:
import numpy as np

## Function 1 - Reshape

Numpy allows us to reshape a matrix provided new shape should be compatible with the original shape.

In [ ]:
a = np.array([1,4,3,2,5,7,6,9,8]).reshape(3,3)
print(a)

here we are just reshaping an simple array

In [ ]:
a = np.array([1,4,3,2,5,7,6,9,8]).reshape(-1,1)
print(a)

Suppose we give row as -1 and 1 as column then Numpy will able to find row as 8.

In [ ]:
a = np.array([1,4,3,2,5,7,6,9,8]).reshape(2,2,-1)
print(a)

If we try to reshape a non-compatible shape or more than one unknown shape then there will be an error message.

In [ ]:
jovian.commit()

## Function 2 - numpy.trace

This is a really cool function that returns sum of values along the diagonal of an array. Arguments taken are -

In [ ]:
a = np.eye(9)
a
np.trace(a)

We created an identity matrix with 9 rows and columns and then calculated sum along the diagonal.

In [ ]:
a = np.eye(9).reshape(3,3,9) * 24
a
np.trace(a)

The values along the 9 diagonals are stored in the returned array.

In [ ]:
a = np.eye(9).reshape(3,3,9) * 24
a
np.trace(a, offset = -0.5)

The offset needs to take an integer value and not float. The offset can be negative or positive which corresponds to below the diagonal and above the diagonal respectively

In [ ]:
jovian.commit()

## Function 3 - Clip

Numpy clip() function is used to Clip (limit) the values in an array. Given an interval, values outside the interval are clipped to the interval edges.

In [ ]:
a = np.array([10, 7, 4, 3, 2, 2, 5, 9, 0, 4, 6, 0])
print (np.clip(a,2,6))

lets put it this way, if an interval of [-1, 1] is specified, values smaller than -1 become -1, and values larger than 1 become 1.

In [ ]:
a = np.array([10, -1, 4, -3, 2, 2, 5, 9, 0, 4, 6, 0])
print (np.clip(a,2,5))

In [ ]:
a = np.array([10, -1, 4, -3, 2, 2, 5, 9, 0, 4, 6, 0])
print (np.clip(a,2))

because we did'nt provided all the necessary values to clip fun.

In [56]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sujalvajire/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/sujalvajire/numpy-array-operations


'https://jovian.ai/sujalvajire/numpy-array-operations'

## Function 3 - count_nonzero

This function can be used to count number of nonzero elements in a NumPy array.

In [57]:
attendance = np.array([[1,0,1], [1,0,1], [1,1,1], [0,0,1], [0,1,1]]) 
attendance
present = np.count_nonzero(attendance, axis =0)

print("student 1 was present for {} days out of 5".format(present[0]))
print("student 2 was present for {} days out of 5".format(present[1]))
print("student 3 was present for {} days out of 5".format(present[2]))

student 1 was present for 3 days out of 5
student 2 was present for 2 days out of 5
student 3 was present for 5 days out of 5


In [58]:
office_leave = np.array([[1,0,1], [1,0,0], [1,1,1]]) 
office_leave
present = np.count_nonzero(office_leave, axis =0)

print("person 1 was present for {} days out of 3".format(present[0]))
print("person 2 was present for {} days out of 3".format(present[1]))
print("person 3 was present for {} days out of 3".format(present[2]))

person 1 was present for 3 days out of 3
person 2 was present for 1 days out of 3
person 3 was present for 2 days out of 3


In [59]:
a = np.array([1,2,3,0,3,1,2,3,1,0,0])
a_nonzero = np.count_nonzero(a, axis = 1) #axis out of bounds
a_nonzero

AxisError: axis 1 is out of bounds for array of dimension 1

As we can see here, the axis provided is out of bounds. Thus we get an error. We should make sure we provide an axis that is in the range as far as dimensions of the array are concerned.

In [ ]:
jovian.commit()

## Function 4 - numpy.where

This is a very interesting conditional function which lets us test a condition and do one operation on those that satisfy the condition and another on those that do not satisfy the condition. Arguments taken are.

In [ ]:
a = np.array([[1,2,3], [4,5,6],[70,80,90]])

b = np.where(a>10, a, 10*a)
print(b)

In [60]:
a = np.array([[1,2,5], [4,1,6],[70,80,3],[7,8,9]])

b = np.where(a>4, a, 10*a)
print(b)

[[10 20  5]
 [40 10  6]
 [70 80 30]
 [ 7  8  9]]


In [61]:
a = np.array([[85,55,43,27,65,45,34,56,76,98],
             [56,76,56,87,98,78,32,12,56,67]]).reshape(10,2)

a_result = np.where(a<35, "fail") #only x provided, breaking point
a_result

ValueError: either both or neither of x and y should be given

We have provided only the x argument along with condition. This is vague and doesn’t tell what to do with values that do not match the condition. We should provide both x and y arguments or neither arguments. When only condition is provided, it acts like np.asarray(condition).nonzero().

In [62]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sujalvajire/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/sujalvajire/numpy-array-operations


'https://jovian.ai/sujalvajire/numpy-array-operations'

## Function 5 - numpy.compress



In [63]:
a = np.array([[1,2], [3,4],[5,6]])
b = np.compress([1, 1, 0], a, axis=0)
b

array([[1, 2],
       [3, 4]])

In [64]:
# Example 2 - working

a = np.array([[2,5,6],[4,1,2],[1,4,3],[7,14,12]])
b = np.compress([True, False, False, True], a, axis = 0)
b

array([[ 2,  5,  6],
       [ 7, 14, 12]])

In [65]:
# Example 3 - breaking (to illustrate when it breaks)

a = np.array([2,5,6])
b = np.compress([True, False, False, True], a, axis = 0)
b

IndexError: index 3 is out of bounds for axis 0 with size 3

Here the Boolean array contains more items than the array a, thus we get an error. We should’ve used only 3 values in the Boolean array as the last “True” doesn’t correspond to anything.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
